// AUTO-GENERATED from the native app's icon sets. Filenames kept as-is.
// path is relative to /assets/icons/<theme>/
export const ICON_SETS: Record<string, string[]> = {
  vice: [
    "Airplane.png",
    "Anchor.png",
    "Barbers.png",
    "Bright button.png",
    "Bust in silhouette.png",
    "Car.png",
    "Cherries.png",
    "Clapper board.png",
    "Clothes.png",
    "Cluckin' Bell.png",
    "Cocktail glass.png",
    "Cup with straw.png",
    "Desert island.png",
    "Diamond with a dot.png",
    "Fork and knife.png",
    "Frame 9-2.png",
    "Game die.png",
    "Gym.png",
    "Hammer.png",
    "Heart.png",
    "Heavy dollar sign.png",
    "Home.png",
    "Optical disk.png",
    "Pizza.png",
    "Safe House.png",
    "Skull.png",
    "Telephone receiver.png",
    "Trophy.png",
    "Videocassette.png",
    "Wrench.png",
  ],
  wasteland: [
    "Anchor_WastelandIcon.svg",
    "Antenna_WastelandIcon.svg",
    "Bridge_WastelandTheme.svg",
    "Brotherhood_WastelandIcon.svg",
    "Camp_WastelandIcon.svg",
    "Camping_WastelandIcon.svg",
    "CarFallout_WastelandIcon.svg",
    "Cave_WastelandIcon.svg",
    "Cinema_WastelandIcon.svg",
    "ClassicalBuilding_WastelandIcon.svg",
    "Clover_WastelandIcon.svg",
    "DestroyedBuilding_WastelandIcon.svg",
    "DestroyedSkyscraper_WastelandIcon.svg",
    "FerrisWheel_WastelandIcon.svg",
    "Field_WastelandIcon.svg",
    "Gear_WastelandIcon.svg",
    "Hill_WastelandIcon.svg",
    "House_WastelandIcon.svg",
    "Nuke_WastelandIcon.svg",
    "Plane_WastelandIcon.svg",
    "Rocket_WastelandIcon.svg",
    "School_WastelandIcon.svg",
    "Star_WastelandIcon.svg",
    "StatueOfLiberty_WastelandIcon.svg",
    "SustensionRailway_WastelandIcon.svg",
    "Tower_WastelandTheme.svg",
    "UFO_WastelandIcon.svg",
  ],
  phantasy: [
    "Cat face.svg",
    "Church.svg",
    "Compass-1.svg",
    "Compass.svg",
    "Crossed swords.svg",
    "Dragon face.svg",
    "Droplet.svg",
    "Feather.svg",
    "Fish.svg",
    "Fork and knife.svg",
    "Four leaf clover.svg",
    "Gem stone.svg",
    "Hook.svg",
    "Money bag.svg",
    "Open book.svg",
    "Paw prints.svg",
    "Pick.svg",
    "Poultry leg.svg",
    "Raised back of hand.svg",
    "Snowman without snow.svg",
    "Sparkle-1.svg",
    "Sparkle.svg",
    "Sparkles.svg",
    "Star of David.svg",
    "Teapot.svg",
  ],
};
